# Generated by Django 3.1.3 on 2021-07-30 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='subjects',
            new_name='subject',
        ),
    ]
